name = "quickeval"
pages_build_output_dir = "dist"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "quickeval"
database_id = "ef431f1d-ad8f-4e4c-9667-9cd17f0f168e"
migrations_dir = "migrations"
