name = "quickeval"
pages_build_output_dir = "dist"
compatibility_date = "2026-10-01"

[[d1_databases]]
binding = "DB"
database_name = "quickeval"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "migrations"
